FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y openjdk-11-jre-headless

RUN pip install kafka-python pyspark influxdb-client

COPY consumer.py /
COPY road_segments.csv /

CMD sleep infinity